career-goal 작성
next-step/career-goal pull request #4
Opened 2023-12-01 10:25 UTC by 0hun

career-goal 작성 리뷰 요청드립니다.

2023-12-01 11:04 UTC, titlet requested changes
goal부분에 개발리더 부분이 있는데 리더쉽 역량에 대한 고민을 추가해보면 좋을것 같습니다.

2023-12-01 11:04 UTC, titlet commented on Career-0hun.md
> +- Spring Batch : 인프런 강의 책 책을 통해 학습 예정
학습만 아니라 지금 운영에서 batch에서 Spring batch를 적용할만한 부분을 찾아 적용해보는 것은 어려운 상황일까요?

2023-12-01 11:04 UTC, titlet commented on Career-0hun.md
> +- 모니터링 환경 구축 및 운영 : 모니터링 환경을 회사 환경에 구축 할 수 있도록 팀원에게 세미나 후 적용 계획
좋은 접근 방법으로 보입니다.

2023-12-01 11:04 UTC, titlet commented on Career-0hun.md
> +### 필요역량
Goal에 개발리더 부분이 있는데 리더쉽 역량은 아직 필요 없을까요?

2023-12-07 06:37 UTC, boorownie requested changes
진달님이 남겨주신 코멘트를 우선 확인해주시면 감사하겠습니다!

2023-12-09 11:56 UTC, boorownie approved these changes
커리어 골 작성하시느라 고생 많으셨습니다.
대략적인 큰 그림은 잘 작성하신 것 같아요!
구체적인 내용은 진달님과의 1:1을 통해 구체화 하면 좋겠습니다 :)

2023-12-09 11:56 UTC, boorownie commented on Career-0hun.md
> +- Spring Batch : 인프런 강의 책 책을 통해 학습 후, 현재 회사에서 batch 서비스에서 개선 할 부분 찾아 개선해보기
👍

2023-12-09 11:56 UTC, boorownie commented on Career-0hun.md
> +- 개발 리더 역량 : 코드 리뷰 및 기술 세미나를 통해 리더쉽 역량 기르기
리더십 역량을 강화한다고 했을 때 리더가 되지 않은 상태에서는 조금은 추상적이고 감이 안 올 수 있습니다.
지금 작성해준 내용은 리더십 역량 중 개발 문화를 만들어갈 수 있는 역량이라고 보이는데 
이 또 한 중요한 역량이라고 생각합니다! 👍

2023-12-09 11:56 UTC, merged