Career Goal 작성
next-step/career-goal pull request #8
Opened 2023-12-02 09:48 UTC by DoLiLu

2023-12-03 02:45 UTC, boorownie requested changes
안녕하세요 정수님!
커리어 골 작성 잘 해주셨습니다.
기술적으로 어떤 고민을 하고 계시고 어떤 방향으로 성장하고 싶은지를 잘 이해할 수 있었습니다.

글을 읽으면서 함께 고민해보면 좋을 내용을 포함해서 코멘트로 남겨놓았습니다.
한번 생각해보시면 좋을 것 같아요~

2023-12-03 02:45 UTC, boorownie commented on Career-Dolilu.md
> +- Kotlin 학습 심화 : 개발에는 문제가 없으나 좀 더 Kotlin을 잘 사용 하도록 학습
지금 계획으로는 코틀린 영역에서는 Gap이 느껴지지는 않네요.
구체적으로 도달하고자 하는 상태가 어느 상태인지가 명확해야 차이를 파악하고 계획을 세울 때 용이할 것 같아요.
물론 도달하고자 하는 상태를 객관적으로 어떤 상태이다라고 표현하기는 쉽지 않지만
이게 불명확 할수록 마음속에 '해야하는 데 어떻게 하지.. 일단 미루자' 생각이 들 가능성이 있을 것 같아요!

나아가고자 하는 방향에 집중하기 위해서 조금 더 구체적인 목적지를 생각해보시거나 Gap에서 빼는 것은 어떨까요?

2023-12-03 02:45 UTC, boorownie commented on Career-Dolilu.md
> +        - 보상 Trasaction 관련 아키텍쳐 설계 및 개발 능력 향상
성장 방향성 및 대상이 구체적임 👍 
능력 향상을 위해서 무엇을 할 수 있을지에 대해서도 고민해보시면 좋을 것 같아요!

2023-12-03 02:45 UTC, boorownie commented on Career-Dolilu.md
> +        - 성능테스트 분석 능력 향상
목표는 스터디를 진행한다, 프로젝트에 적용해본다 와 같이 내가 수행해서 달성 여부를 판단할 수 있으면 좋습니다.
능력 향상을 할 수 있는 방법과 어느 정도의 능력을 향상했을 때 완수 했다라고 판단할 수 있을 지에 대한 기준도 있으면 좋겠어요!
이 부분이 없으면 영원히 해결되지 않는 투두리스트가 될 수 있어요.

2023-12-03 02:45 UTC, boorownie commented on Career-Dolilu.md
> +    - 모니터링 기술 : Grafana, datadog, cloudwatch 같은 모니터링 툴을 사용하는 환경 구축 능력 스터디
모니터링도 단순히 환경을 구축하는 것을 넘어서 규모에 따라 모니터링을 구축하기 위해 장비의 부하가 얼마나 걸리는지, 그리고 효율적인 인프라 구성에 대해서도 고민해야 할 수 있습니다. 이러한 부분은 실제로 경험해보기 전에는 알기 어렵고 스터디를 하더라도 내 역량이라고 하기 어려울 수 있어요.

최대한 다양한 사례들을 많이 접하고 실제로 문제를 해결해야하는 상황에 적용해볼 수 있게 하는게 좋을 것 같아요.
모니터링 기술과 관련된 투두 리스트에 이러한 부분도 함께 고려해보시면 좋겠어요.

2023-12-03 02:45 UTC, boorownie commented on Career-Dolilu.md
> +### 필요 역량
리딩을 하고 계신다고 하셨는데 상황에 따라 개발 역량 만큼 리더십 역량이 중요한 경우가 있더라구요.
혹시 이 부분에 대해서는 필요 역량으로 고민해보셨을까요?

2023-12-03 08:50 UTC, DoLiLu commented on Career-Dolilu.md
> +### 필요 역량
이 부분을 쓸까 말까 하다가 어떻게 해야할지 모르겠어서 뺐었는데 말씀하신대로 필요 역량이라고 생각합니다.

2023-12-04 03:23 UTC, boorownie approved these changes
피드백 반영 확인했습니다!

저는 Goal이라는게 목표로서의 역할과 함께 현재 기대하는 성장의 방향성이라고 생각이 듭니다.
따라서 한번 정한다고 이대로 지켜야 한다고 생각하기 보다는 성장 하는 과정에서 지속적으로 변경하고 관리해야 한다고 생각해요! 

지금도 충분히 좋은 Goal이지만 앞으로 이 과정을 진행하면서 더 명확한 방향성을 바라볼 수 있게되면 좋을 것 같습니다! 고생 많으셨습니다.

2023-12-04 03:23 UTC, boorownie commented on Career-Dolilu.md
> +  - 팀의 구성원이 많아도 잘 이끌수 있는 능력
이끈다는 표현도 조금 여러가지를 함축하고 있는 것 같아요! 
예를 들면 팀의 성과를 도출한다, 구성원들과의 신뢰를 형성한다 등등
목표가 구체적이면 달성하기도 계획을 세우기도 편해지니 이 점 참고해주세요!

2023-12-04 03:23 UTC, boorownie commented on Career-Dolilu.md
> +  - 함께 성장할 수 있는 환경 갖추는 능력 부족
프로젝트를 함께 하는 개발자 분들에게 시니어 혹은 리드로서의 영향향을 끼치기 위해서는
프로젝트의 일정과 진행 상황, 리소스 투입 상황 등을 큰 그림 관점으로 볼 수 있으면 좋을 것 같아요!
나의 상태 부분에 이러한 점이 빠져있는 것 같아서 혹시 추가가 필요하다면 참고해보세요 :)

2023-12-04 03:23 UTC, boorownie commented on Career-Dolilu.md
> +        - 성능 테스트 결과 및 트래픽, 부하 관련 학습을 하여 서버 및 네트워크 스펙에 따른 아키텍쳐 설계 능력 향상
👍

2023-12-04 03:23 UTC, merged